version: '3.8'

services:
  app:
    image: ghcr.io/mikhail-angelov/poll-maker:latest
    container_name: poll-maker
    ports:
      - "127.0.0.1:3014:3001"
    volumes:
      - ./poll-maker.sqlite:/app/poll-maker.sqlite
    env_file:
      - ./.env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    command: node dist/server/index.js

  monic-poll-maker:
    image: ghcr.io/mikhail-angelov/monic:latest
    container_name: monic-poll-maker
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - app
    env_file:
      - ./.env
    environment:
      - MONIC_APP_NAME=pollMakerMonitor

      - MONIC_CHECK_SYSTEM_INTERVAL=60
      - MONIC_CHECK_SYSTEM_CPU_THRESHOLD=80
      - MONIC_CHECK_SYSTEM_MEMORY_THRESHOLD=85
      - MONIC_CHECK_SYSTEM_DISK_THRESHOLD=90

      - MONIC_CHECK_DOCKER_INTERVAL=60
      - MONIC_CHECK_DOCKER_CONTAINERS=poll-maker

      - MONIC_CHECK_HTTP_INTERVAL=300
      - MONIC_CHECK_HTTP_URL=http://localhost:3010
      - MONIC_CHECK_HTTP_METHOD=GET
      - MONIC_CHECK_HTTP_TIMEOUT=10
      - MONIC_CHECK_HTTP_EXPECTED_STATUS=200
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
