export const errorCodes = {
  POLL_NAME_REQUIRED: 'POLL_NAME_REQUIRED',
  POLL_DETAILS_REQUIRED: 'POLL_DETAILS_REQUIRED',
  QUESTIONS_REQUIRED: 'QUESTIONS_REQUIRED',
  QUESTION_NAME_REQUIRED: 'QUESTION_NAME_REQUIRED',
  QUESTION_TEXT_REQUIRED: 'QUESTION_TEXT_REQUIRED',
  QUESTION_OPTIONS_REQUIRED: 'QUESTION_OPTIONS_REQUIRED',
  ANSWER_REQUIRED: 'ANSWER_REQUIRED',
  ANSWER_OPTION_INVALID: 'ANSWER_OPTION_INVALID',
  ANSWER_MULTIPLE_NOT_ALLOWED: 'ANSWER_MULTIPLE_NOT_ALLOWED',
  ADMIN_HASH_REQUIRED: 'ADMIN_HASH_REQUIRED',
  ADMIN_HASH_INVALID: 'ADMIN_HASH_INVALID',
  POLL_NOT_FOUND: 'POLL_NOT_FOUND'
} as const;